### ISSUE TITLE
Old ADB version makes the app stuck on loading

### ISSUE THREAD

**Issue by Simizfo** [Simizfo/WSATools#2]
[This ADB package](https://forum.xda-developers.com/t/official-tool-windows-adb-fastboot-and-drivers-15-seconds-adb-installer-v1-4-3.2588979/) contains an old version of ADB which makes the app get stuck on loading indefinitely

Expected behavior:
The app doesn't get stuck, or provides a way to update ADB

**Comment by Simizfo** [comment]
This has been reported on issue #11.

**Comment by Simizfo** [comment]
**Here's a temporary manual fix, if you know what you're doing**:

Check your "path" environment variable, and look for a line that points to a folder named "platform-tools" or a folder that contains adb.exe and fastboot.exe. Remove that line, and WSATools will work fine.

**Comment by Simizfo** [comment]
This should be fixed, will be available when 0.2.0 releases.

Thanks everyone that reported it!

**Comment by Johnjr00** [comment]
> **Here's a temporary manual fix, if you know what you're doing**:
> 
> Check your "path" environment variable, and look for a line that points to a folder named "platform-tools" or a folder that contains adb.exe and fastboot.exe. Remove that line, and WSATools will work fine.

I removed the ADB folder from the Windows "path", but I'm still having this same issue with infinite "Loading" after selecting an APK... Any ideas? Thanks!

**Comment by Simizfo** [comment]
Next version fixes this. I've been stuck with university, sorry for that. Next week probably.

**Comment by Azertixe** [comment]
Same issue here :(

**Comment by Azertixe** [comment]
Hello. I have infinite "Loading" after installation process. I did some
tests, it should be caused by an incompatible app : Yatse. Perhaps not
working in emulated environment?
I tried with Telegram and i don't have the problem.

Thanks for your help

Le mar. 30 août 2022 à 03:10, Simone Franco ***@***.***> a
écrit :
