### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by AlexZedTech** [Simizfo/WSATools#33]

**Comment by Simizfo** [comment]
This needs more details, please! 

Thank you.

**Comment by Simizfo** [comment]
Closing as there was no more details provided. Feel free to reopen this if needed.

**Comment by Azertixe** [comment]
Hello same issue here. Wich details do you need ?

**Comment by Simizfo** [comment]
What steps did you do?

Anything that might help me understand where the code fails is welcome. Thanks!

**Comment by Diegorro98** [comment]
I reproduced the issue following these steps.
1. Install WSATools
2. Try install an APK.
3. Install ADB from WSATools dialog
4. When ADB is installed, cancel APK installation (if installation was made from WSATools just close the APK file selection window so that WSATools is back at the start page, if it was made by double-clicking on an APK file on the file explorer or you already have chosen an APK, close the window when the option to install is shown)
5. Try again to install again the APK

**Comment by Simizfo** [comment]
Thanks for this @Diegorro98, I'll try to reproduce it and see what happens.

**Comment by zeratax** [comment]
yea also stuck here. I can install this apk manually via cli, but the tool is just stuck like this
![image](https://user-images.githubusercontent.com/5024958/210865896-4921d57f-e576-49ca-8983-273f2882e9ee.png)

**Comment by Saplyn** [comment]
Here are 2 possible causes of Infinite Loading on my machine.

**Background Information**

- Installed WSA, Amazon Appstore and WSA-Tools through Microsoft Store.
- Has some complete and installable APK files.
- Has a valid and working ADB package, version 1.0.41, added to PATH.
- Developer Mode enabled in WSA Settings, port set to default.
- Subsystem Resources set to Continues, in WSA Settings.
- Custom ADB Location set correctly.

**Cause 1: ADB "debugs" for the first time, WSA not allowing debug from strange device**

- I have never installed anything besides Amazon Appstore in WSA, nor do I ever launch ADB.
- I failed (infinite Loading) to install the APK through: (I call it *method 1*)
  - Launch WSA-Tools
  - Click "install an APK"
  - Choose the APK file
  - Click "Load APK"
- I failed (infinite Loading) to install the APK through: (I call it *method 2*)
  - Double Clicking it.
- I opened PowerShell, typed `adb connect 127.0.0.1:58526`, a window popped up and ask me "allow debugging?", I checked the checkbox "always allow" and then clicked "allow". (texts in `""` may not the same, but the meanings are)
- I typed `adb install <path to APK 1>`, and successfully installed one app. (yes, through command line)
- I successfully installed another APK through *method 1*.

**Cause 2: disconnect and re-connect WSA in command line**

- I installed an APK through *method 2*, succeeded.
- ~~For some reason I decided to~~ disconnected WSA in command line by typing `adb disconnect` in PowerShell.
- I re-connect WSA in command line using `abd connect 127.0.0.1:58526`
- I typed `abd devices` to confirm if it's connected, and it was.
- I tried to install another APK through *method 1*, failed (Infinite Loading).
- I tried to install the same APK in the last step through command line, succeeded.

**Comment by Simizfo** [comment]
Hi there! Good news: WSATools has been 100% rewritten from scratch using Windows App SDK. 
It's WAY more stable.

I'll release this as soon as possible!

Thanks for reporting.

**Comment by Simizfo** [comment]
This should be fixed in the new version (1.0.0) available now on the store, if anyone happens to try please let me know and I'll close this!

**Comment by BlankFX1** [comment]
Infinite Loading still happens on my freshly installed WSATools right after selecting a custom adb folder.
WSATools just hangs forever, including becomming a "white" app when clicking somewhere.

(As I already have adb around, I'm not planning to download another via WSATools.)

**Comment by Simizfo** [comment]
@BlankFX1 Would you mind posting your logs? Open them in the app main page before selecting a custom ADB in settings.

**Comment by BlankFX1** [comment]
Sure, but I highly doubt this will help:

```
CORE: Checking for WSA ...
CORE: Checking for WSA returned 0
CORE: Checking for WSA ...
CORE: Checking for WSA returned 0
```
Thats all.
And just to clarify; WSA itself works perfectly fine.

**Comment by Simizfo** [comment]
This is interesting, apparently no error. I'll check if something blocking might happen there. Thanks for reporting!
